//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Fwk.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FwkResourcesService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FwkResourcesService() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ark.Fwk.Service.Properties.FwkResourcesService", typeof(FwkResourcesService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Captions/FwkCaptionDuplicatedData.
        /// </summary>
        public static string FwkCaptionDuplicatedData {
            get {
                return ResourceManager.GetString("FwkCaptionDuplicatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Captions/FwkCaptionInvalidData.
        /// </summary>
        public static string FwkCaptionInvalidData {
            get {
                return ResourceManager.GetString("FwkCaptionInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Captions/FwkCaptionMissingData.
        /// </summary>
        public static string FwkCaptionMissingData {
            get {
                return ResourceManager.GetString("FwkCaptionMissingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Captions/FwkCaptionMissingProperty.
        /// </summary>
        public static string FwkCaptionMissingProperty {
            get {
                return ResourceManager.GetString("FwkCaptionMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Captions/FwkCaptionNotFound.
        /// </summary>
        public static string FwkCaptionNotFound {
            get {
                return ResourceManager.GetString("FwkCaptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordDataSetMissing.
        /// </summary>
        public static string FwkExceptionRecordDataSetMissing {
            get {
                return ResourceManager.GetString("FwkExceptionRecordDataSetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordDataTableEmpty.
        /// </summary>
        public static string FwkExceptionRecordDataTableEmpty {
            get {
                return ResourceManager.GetString("FwkExceptionRecordDataTableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordDataTableMissing.
        /// </summary>
        public static string FwkExceptionRecordDataTableMissing {
            get {
                return ResourceManager.GetString("FwkExceptionRecordDataTableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordKeyFieldEmpty.
        /// </summary>
        public static string FwkExceptionRecordKeyFieldEmpty {
            get {
                return ResourceManager.GetString("FwkExceptionRecordKeyFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordKeyFieldMissing.
        /// </summary>
        public static string FwkExceptionRecordKeyFieldMissing {
            get {
                return ResourceManager.GetString("FwkExceptionRecordKeyFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordNonEditableFieldModified.
        /// </summary>
        public static string FwkExceptionRecordNonEditableFieldModified {
            get {
                return ResourceManager.GetString("FwkExceptionRecordNonEditableFieldModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordOriginalKeyNotFound.
        /// </summary>
        public static string FwkExceptionRecordOriginalKeyNotFound {
            get {
                return ResourceManager.GetString("FwkExceptionRecordOriginalKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordRequiredFieldEmpty.
        /// </summary>
        public static string FwkExceptionRecordRequiredFieldEmpty {
            get {
                return ResourceManager.GetString("FwkExceptionRecordRequiredFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordUniqueFieldDuplicatedDatabase.
        /// </summary>
        public static string FwkExceptionRecordUniqueFieldDuplicatedDatabase {
            get {
                return ResourceManager.GetString("FwkExceptionRecordUniqueFieldDuplicatedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Fwk.Language.{0}.Service/Exceptions/FwkExceptionRecordUniqueFieldDuplicatedRequest.
        /// </summary>
        public static string FwkExceptionRecordUniqueFieldDuplicatedRequest {
            get {
                return ResourceManager.GetString("FwkExceptionRecordUniqueFieldDuplicatedRequest", resourceCulture);
            }
        }
    }
}
