//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Sys.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SysResourcesService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysResourcesService() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ark.Sys.Service.Properties.SysResourcesService", typeof(SysResourcesService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionIdDomain.
        /// </summary>
        public static string SysCaptionIdDomain {
            get {
                return ResourceManager.GetString("SysCaptionIdDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionIdRole.
        /// </summary>
        public static string SysCaptionIdRole {
            get {
                return ResourceManager.GetString("SysCaptionIdRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionInvalidType.
        /// </summary>
        public static string SysCaptionInvalidType {
            get {
                return ResourceManager.GetString("SysCaptionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionName.
        /// </summary>
        public static string SysCaptionName {
            get {
                return ResourceManager.GetString("SysCaptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionSuccess.
        /// </summary>
        public static string SysCaptionSuccess {
            get {
                return ResourceManager.GetString("SysCaptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Exceptions/SysExceptionAutomationInvalidService.
        /// </summary>
        public static string SysExceptionAutomationInvalidService {
            get {
                return ResourceManager.GetString("SysExceptionAutomationInvalidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Messages/SysMessageSuccess.
        /// </summary>
        public static string SysMessageSuccess {
            get {
                return ResourceManager.GetString("SysMessageSuccess", resourceCulture);
            }
        }
    }
}
