//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Sys.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SysResourcesService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysResourcesService() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ark.Sys.Service.Properties.SysResourcesService", typeof(SysResourcesService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionDataTableMissing.
        /// </summary>
        public static string SysCaptionDataTableMissing {
            get {
                return ResourceManager.GetString("SysCaptionDataTableMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionDataTableMissingField.
        /// </summary>
        public static string SysCaptionDataTableMissingField {
            get {
                return ResourceManager.GetString("SysCaptionDataTableMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Captions/SysCaptionDataTableMissingRow.
        /// </summary>
        public static string SysCaptionDataTableMissingRow {
            get {
                return ResourceManager.GetString("SysCaptionDataTableMissingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Exceptions/SysExceptionDataTableRoleMissing.
        /// </summary>
        public static string SysExceptionDataTableRoleMissing {
            get {
                return ResourceManager.GetString("SysExceptionDataTableRoleMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Exceptions/SysExceptionDataTableRoleMissingFieldIdDomain.
        /// </summary>
        public static string SysExceptionDataTableRoleMissingFieldIdDomain {
            get {
                return ResourceManager.GetString("SysExceptionDataTableRoleMissingFieldIdDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Exceptions/SysExceptionDataTableRoleMissingFieldIdRole.
        /// </summary>
        public static string SysExceptionDataTableRoleMissingFieldIdRole {
            get {
                return ResourceManager.GetString("SysExceptionDataTableRoleMissingFieldIdRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Exceptions/SysExceptionDataTableRoleMissingFieldName.
        /// </summary>
        public static string SysExceptionDataTableRoleMissingFieldName {
            get {
                return ResourceManager.GetString("SysExceptionDataTableRoleMissingFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Sys.Language.{0}.Service/Exceptions/SysExceptionDataTableRoleMissingRows.
        /// </summary>
        public static string SysExceptionDataTableRoleMissingRows {
            get {
                return ResourceManager.GetString("SysExceptionDataTableRoleMissingRows", resourceCulture);
            }
        }
    }
}
