//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ark.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ark.Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionBase]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Package [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_Base {
            get {
                return ResourceManager.GetString("Ark_New_Project_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionData]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Package [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_Data {
            get {
                return ResourceManager.GetString("Ark_New_Project_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionIPlugin]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Pack [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_IPlugin {
            get {
                return ResourceManager.GetString("Ark_New_Project_IPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionIServer]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Pack [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_IServer {
            get {
                return ResourceManager.GetString("Ark_New_Project_IServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionIService]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Pac [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_IService {
            get {
                return ResourceManager.GetString("Ark_New_Project_IService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionServant]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Pack [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_Servant {
            get {
                return ResourceManager.GetString("Ark_New_Project_Servant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk.Web&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionServer]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;NoDefaultLaunchSettingsFile&gt;true&lt;/NoDefaultLaunchSettingsFil [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_Server {
            get {
                return ResourceManager.GetString("Ark_New_Project_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;TargetFramework&gt;[arkNetFramework]&lt;/TargetFramework&gt;
        ///    &lt;Version&gt;[arkVersion]&lt;/Version&gt;
        ///    &lt;Authors&gt;[arkAuthor]&lt;/Authors&gt;
        ///    &lt;Product&gt;[arkProduct]&lt;/Product&gt;
        ///    &lt;Description&gt;[arkProjectDescriptionService]&lt;/Description&gt;
        ///    &lt;Copyright&gt;Copyleft (ͻ) [arkYear]&lt;/Copyright&gt;
        ///    &lt;PackageLicenseFile&gt;LICENSE&lt;/PackageLicenseFile&gt;
        ///    &lt;RepositoryUrl&gt;[arkRepository]&lt;/RepositoryUrl&gt;
        ///    &lt;GeneratePackageOnBuild&gt;true&lt;/GeneratePackageOnBuild&gt;
        ///    &lt;Pack [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Project_Service {
            get {
                return ResourceManager.GetString("Ark_New_Project_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio Version 16
        ///VisualStudioVersion = 16.0.30907.101
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{2150E333-8FDC-42A3-9474-1A3956D46DE8}&quot;) = &quot;[arkSolutionFolderNameBase]&quot;, &quot;[arkSolutionFolderNameBase]&quot;, &quot;{[arkSolutionFolderGuidBase]}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;[arkProjectNameBase]&quot;, &quot;[arkSolutionFolderNameBase]\[arkProjectFolderNameBase]\[arkProjectNameBase].csproj&quot;, &quot;{[arkProjectGuidBa [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Ark_New_Solution {
            get {
                return ResourceManager.GetString("Ark_New_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Std.Language.{0}/Captions/StdCaptionCancel.
        /// </summary>
        public static string StdCaptionCancel {
            get {
                return ResourceManager.GetString("StdCaptionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Ark.Std.Language.{0}/Messages/StdMessageCancelCurrentEdition.
        /// </summary>
        public static string StdMessageCancelCurrentEdition {
            get {
                return ResourceManager.GetString("StdMessageCancelCurrentEdition", resourceCulture);
            }
        }
    }
}
